### ISSUE TITLE
Crash on Apple Silicon

### ISSUE THREAD

**Issue by LionZXY** [SinTh0r4s/HydroEnergy#32]
Hi! I see that on MacOS we have some opengl problem (https://github.com/SinTh0r4s/HydroEnergy/issues/23), but also i see that you add workaround for this and now game shouldn't crashed.

But GregTech New Horizion with latest version of this mod crashed on my MacBook Air (M1, 2020) with this exception:
```
Description: Unexpected error

org.lwjgl.opengl.OpenGLException: Invalid operation (1282)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at org.lwjgl.opengl.GL20.glUniformMatrix4(GL20.java:511)
	at com.sinthoras.hydroenergy.client.renderer.HEProgram.setViewProjection(HEProgram.java:150)
	at com.sinthoras.hydroenergy.client.renderer.HETessalator.render(HETessalator.java:140)
	at net.minecraft.client.renderer.EntityRenderer.redirect$redirectRenderEntities$zde000(EntityRenderer.java:3074)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1337)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Could you, please, fix this or describe workaround? I can help you to fix/debug it

**Comment by LionZXY** [comment]
Fixed by https://github.com/GTNewHorizons/HydroEnergy/pull/18
